version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html

hooks:
  AfterInstall:
    - location: terraform-project-task-1-main/terraform-project-task-1-main/scripts/install.sh
      timeout: 300
      runas: root