version: 0.2

phases:
  install:
    commands:
      - echo "Install phase started"
  build:
    commands:
      - echo "Build phase started"
      - echo "No application build required, just provisioning"
artifacts:
  files:
    - '**/*'
